### ISSUE TITLE
Device id dont update, when delete another device

### ISSUE THREAD

**Issue by SOliver78** [TasmoAdmin/TasmoAdmin#713]
If I add 4 devices with more than 1 friendly name (eg Gosund P1 or Nous A5T), then delete id 2, id 3 is updated in 2 and id 4 in 3, but not when editing the settings, there it is still id 3 (look at screenshots):

![2022-11-22 20_28_01-](https://user-images.githubusercontent.com/107271539/203405253-1804cad1-a873-4ad3-9c51-b9314ec0f878.png)
![2022-11-22 20_30_34-Module - TasmoAdmin – Mozilla Firefox](https://user-images.githubusercontent.com/107271539/203405295-c9d098c3-8604-4d7a-b370-80fe5141cc1f.png)

Sorry for my bad english ;)

**Comment by inverse** [comment]
Not sure I understand the problem in detail but perhaps I could explain something.

Each device gets given a unique ID which is what you're seeing on the URL. You can see this in the CSV file that TasmoAdmin persists.

Along with this each device has a position, which is that column on the left which is more to do with ordering within the UI.

Perhaps this is what you're seeing or is it something else?

**Comment by SOliver78** [comment]
When i delete an Gosund P1 or Nous A5T at Position2 and ID 2, the next device with ID 3 becomes position 2.

But when i delete an non Gosung P1 or Nous A5T device at position 2, the next device receives no new position2, shows in the next screenshot:
![2022-11-22 22_26_50-Temp](https://user-images.githubusercontent.com/107271539/203425256-3cf0e835-2a09-436e-8ebd-7cc5542756e6.png)

**Comment by inverse** [comment]
That's strange - Yeah I've not seen that behaviour. Only the one where if you delete it it gets removed and the sequence broken.

**Comment by SOliver78** [comment]
I have insert to my 2.1.1 install, but no change for me.

**Comment by inverse** [comment]
Just pushed a change which might help with it.

Are you able to try out this release? https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.2.0-beta.4

**Comment by SOliver78** [comment]
I tested version 2, but unfortunately no change.

![2022-11-30 08_23_28-PowerShell läuft nicht_ Mit diesen 5 Tricks schon › DiszipLean – Mozilla Firefox](https://user-images.githubusercontent.com/107271539/204733682-30de84de-397d-4e69-b1bc-37029169f757.png)

**Comment by inverse** [comment]
Sorry was sick for a while - I suspect this is due to the `devices.csv` file being in a corrupted state due to conflicting IDs.

Are you able to modify the CSV file so that the first column has unique values?

**Comment by SOliver78** [comment]
I hope you are well again?
I always delete the device.csv before running an auto scan.
How do I have to edit the file so that the first line is unique?
Can you provide me a device.csv?

**Comment by inverse** [comment]
Thanks - much better :)

Interesting - then it should be fine. That left column is the IDs which should be unique

![image](https://user-images.githubusercontent.com/713525/206021893-982f8374-2fbe-4f3e-a8f0-90c40d4da2bf.png)


As for the duplicated positions - that's also strange - I pushed a change yesterday which added some tests to how that's computed and it seems fine :/ I'm curious what's causing it for you.

https://github.com/TasmoAdmin/TasmoAdmin/pull/724/files

**Comment by SOliver78** [comment]
I tested version 2.2.0, the problem still seems to be there.
![2022-12-14 22_46_54-](https://user-images.githubusercontent.com/107271539/207723215-b76bfbad-c278-4e82-bcd3-6f3b8c257c90.png)

This is what devices.csv looks like after deleting device 2:
![2022-12-14 22_51_27-WSVM old (wsvmold_0) – VNC Viewer](https://user-images.githubusercontent.com/107271539/207723374-fa8f96f7-ddf8-4e42-84c4-a21fd3139440.png)

**Comment by SOliver78** [comment]
No, when i delete a device, i delete device.csv and scan all device new.
